version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/bitnami
    networks:
      - picms-net
    environment:
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=pi_cms
    restart: 'no'

  nginx:
      image: pi-cms-nginx:1.0.0
      container_name: pi-cms-nginx
      build:
          context: .
          dockerfile: Dockerfile-nginx
      #networks:
      #    - picms-net
      network_mode: host
      depends_on:
          - mongodb
      volumes:
          - ./nginx/conf/sites-enabled:/etc/nginx/sites-enabled
          - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/ssl:/etc/nginx/ssl
      ports:
          - '80:80'
          - '443:443'
    #      - '27017:27017'
      restart: 'no'

  # backend:
  #     image: pi-cms-backend:0.1.0
  #     container_name: pi-cms-backend
  #     build:
  #         context: .
  #         dockerfile: Dockerfile-backend
  #     volumes:
  #         - ./.env:/usr/src/app/.env
  #         - ./_projects:/usr/src/app/_projects
  #     depends_on:
  #         - mongodb
  #     ports:
  #         - "5000:5000"
  #     network_mode: host
  #     restart: 'always'

networks:
    picms-net:
        driver: bridge
