version: '3'

services:
    nginx:
#        image: project-nginx:1.0.0
        container_name: project-nginx
        build:
            context: .
            dockerfile: Dockerfile-nginx
        networks:
            - project-net
        volumes:
            - ./nginx/conf/conf.d:/etc/nginx/conf.d
            - ./nginx/ssl:/etc/nginx/ssl
        ports:
            - '8080:80'
            - '8443:443'
        restart: always
    frontend:
        container_name: project-frontend
#        image: project-frontend:2.0.19
        build:
            context: .
            dockerfile: Dockerfile-app
        networks:
            - project-net
        volumes:
            - ./.env:/usr/src/app/.env
        ports:
            - '3000'
        restart: always
networks:
    project-net:
        driver: bridge
